### ISSUE TITLE
[Bug Report] Want to remove/hide vuetify theme stylesheet from page source

### ISSUE THREAD

**Issue by kamleshkatpara** [vuetifyjs/nuxt#47] opened 2018-07-10 15:06 UTC
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 8, Linux

### Steps to reproduce
none

### Expected Behavior
should remove/hide vuetify theme stylesheet from page source

### Actual Behavior
shows vuetify theme stylesheet from page source

### Reproduction Link
[https://codepen.io/zikeji/pen/ypeQNm](https://codepen.io/zikeji/pen/ypeQNm)

![capture](https://user-images.githubusercontent.com/16983847/42519057-0c5a55ae-8418-11e8-96cc-ab71bf5df3be.PNG)

**Comment by KaelWD** [comment] 2018-07-14 13:41
Duplicate of vuetifyjs/vuetify#3349

**Closed by KaelWD** 2018-07-14 13:41 UTC
